/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HairRouteImport } from './routes/hair'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as IndexRouteImport } from './routes/index'

const HairRoute = HairRouteImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/hair': typeof HairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/hair': typeof HairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/hair': typeof HairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fashion' | '/hair'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fashion' | '/hair'
  id: '__root__' | '/' | '/fashion' | '/hair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FashionRoute: typeof FashionRoute
  HairRoute: typeof HairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hair': {
      id: '/hair'
      path: '/hair'
      fullPath: '/hair'
      preLoaderRoute: typeof HairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FashionRoute: FashionRoute,
  HairRoute: HairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
